services:
  mongodb:
    image: mongo:7.0
    container_name: todo-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: todos
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network

  # Optional: MongoDB Express for web-based admin interface


volumes:
  mongodb_data:

networks:
  todo-network:
    driver: bridge
