name: Docker Compose CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: chachalitkh
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: build and tag docker images
      run: |
        docker compose -f docker-compose.yml build
    
    - name: tag and push backend image
      run: |
        docker tag todo101-todo-backend:latest chachalitkh/todo-backend:latest
        docker push chachalitkh/todo-backend:latest

    - name: tag and push frontend image
      run: |
        docker tag todo101-todo-frontend:latest chachalitkh/todo-frontend:latest
        docker push chachalitkh/todo-frontend:latest
      